#!/usr/bin/env python3.11

import os
import re
from pathlib import Path
from sys import version_info as ver

import click
from click import secho


@click.command()
@click.argument('number', type=int)
@click.argument('title')
def main(number, title):
    """
    Start a new solution for the Project Euler problem with
    the given TITLE and NUMBER.
    """
    title = re.sub(r'\s+', '-', title.lower().strip())
    name = f'{number}-{title}'

    dir = Path(name)
    try:
        dir.mkdir(0o755)
    except FileExistsError:
        secho(f'{name} already exists! 🤔', fg='red')
        return

    with open(dir / '__main__.py', 'w') as f:
        f.write(PYTHON_TEMPLATE)

    secho(f'Started new solution in {name}! Get coding 🤩',
          fg='green', bold=True)


PYTHON_TEMPLATE = f'''#!/usr/bin/env python{ver.major}.{ver.minor}

import click


@click.command()
def main():
    pass


start = Arrow.now()
main()
echo(f'Execution time: {start.humanize(only_distance=True)}')
'''

main()
